//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotBrokerSpec) DeepCopyInto(out *PinotBrokerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotBrokerSpec.
func (in *PinotBrokerSpec) DeepCopy() *PinotBrokerSpec {
	if in == nil {
		return nil
	}
	out := new(PinotBrokerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotCluster) DeepCopyInto(out *PinotCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotCluster.
func (in *PinotCluster) DeepCopy() *PinotCluster {
	if in == nil {
		return nil
	}
	out := new(PinotCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PinotCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotClusterList) DeepCopyInto(out *PinotClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PinotCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotClusterList.
func (in *PinotClusterList) DeepCopy() *PinotClusterList {
	if in == nil {
		return nil
	}
	out := new(PinotClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PinotClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotClusterSpec) DeepCopyInto(out *PinotClusterSpec) {
	*out = *in
	in.Zookeeper.DeepCopyInto(&out.Zookeeper)
	in.Controller.DeepCopyInto(&out.Controller)
	in.Broker.DeepCopyInto(&out.Broker)
	in.Server.DeepCopyInto(&out.Server)
	in.Minion.DeepCopyInto(&out.Minion)
	in.Pod.DeepCopyInto(&out.Pod)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotClusterSpec.
func (in *PinotClusterSpec) DeepCopy() *PinotClusterSpec {
	if in == nil {
		return nil
	}
	out := new(PinotClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotClusterStatus) DeepCopyInto(out *PinotClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotClusterStatus.
func (in *PinotClusterStatus) DeepCopy() *PinotClusterStatus {
	if in == nil {
		return nil
	}
	out := new(PinotClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotComponentResources) DeepCopyInto(out *PinotComponentResources) {
	*out = *in
	in.ResourceRequirements.DeepCopyInto(&out.ResourceRequirements)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotComponentResources.
func (in *PinotComponentResources) DeepCopy() *PinotComponentResources {
	if in == nil {
		return nil
	}
	out := new(PinotComponentResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotControllerSpec) DeepCopyInto(out *PinotControllerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotControllerSpec.
func (in *PinotControllerSpec) DeepCopy() *PinotControllerSpec {
	if in == nil {
		return nil
	}
	out := new(PinotControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotMinionSpec) DeepCopyInto(out *PinotMinionSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotMinionSpec.
func (in *PinotMinionSpec) DeepCopy() *PinotMinionSpec {
	if in == nil {
		return nil
	}
	out := new(PinotMinionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotPodSettings) DeepCopyInto(out *PinotPodSettings) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotPodSettings.
func (in *PinotPodSettings) DeepCopy() *PinotPodSettings {
	if in == nil {
		return nil
	}
	out := new(PinotPodSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotServerSpec) DeepCopyInto(out *PinotServerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.Storage = in.Storage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotServerSpec.
func (in *PinotServerSpec) DeepCopy() *PinotServerSpec {
	if in == nil {
		return nil
	}
	out := new(PinotServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotServerStorageSpec) DeepCopyInto(out *PinotServerStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotServerStorageSpec.
func (in *PinotServerStorageSpec) DeepCopy() *PinotServerStorageSpec {
	if in == nil {
		return nil
	}
	out := new(PinotServerStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotZookeeperExternal) DeepCopyInto(out *PinotZookeeperExternal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotZookeeperExternal.
func (in *PinotZookeeperExternal) DeepCopy() *PinotZookeeperExternal {
	if in == nil {
		return nil
	}
	out := new(PinotZookeeperExternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotZookeeperSpec) DeepCopyInto(out *PinotZookeeperSpec) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(PinotZookeeperExternal)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotZookeeperSpec.
func (in *PinotZookeeperSpec) DeepCopy() *PinotZookeeperSpec {
	if in == nil {
		return nil
	}
	out := new(PinotZookeeperSpec)
	in.DeepCopyInto(out)
	return out
}
